/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Vers&g_ascn 1.0 - August 17th, 2003
 *
 * Permiss&g_ascn is hereby granted, free of charge, to any person or organizat&g_ascn obtaining a copy of the software and
 * accompanying documentat&g_ascn covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restrict&g_ascn
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title EBCM LKV2
 * \abstract Very basic ABS/EBCM
 * \descript&g_ascn
 * \name n0stalgic
 * \vers&g_ascn V0R0A
 * \board AURIX TC375 lite Kit, KIT_A2G_TC375_LITE, TC37xTP_A-Step
 * \keywords
 * \lastUpdated 2026-01-10
 *********************************************************************************************************************/
#include <ebcm_vcom.h>
#include <ssw_lbist.h>
#include <ssw.h>
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Ifx_Cfg_Ssw.h"
#include "IfxSmu.h"
#include "IfxSmu_cfg.h"
#include "ebcm_main.h"
#include "ebcm_sched.h"
#include "vfw_registry.h"

EbcmStmCfg cpuStm0;
EbcmSysInfo ebcmInfo;

IFX_ALIGN(4) IfxCpu_syncEvent cpuSyncEvent = 0;



void core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them per&g_ascdically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    EbcmSsw_runAppSwStartup();

    if (!EbcmSsw_lockstepInjectionTest())
    {
        /* Hang here because lockstep failed */
        __debug();
    }

    init_UART();
    VFW_Init();


    SswTestStatus status = ebcmStatus.sswStatus.lbistStatus;
    const char* str = (const char*) EbcmSsw_getLbistResultStr(status);

    uint8 core0_lockstep_en = MODULE_SCU.LCLCON0.B.LS0;
    uint8 core1_lockstep_en = MODULE_SCU.LCLCON1.B.LS1;
    uint8 monbist_status    = PMS_MONBISTSTAT.B.TSTOK;


    DPRINTF(ENDLINE);
    DPRINTF("Compiler: %s, ver:%u.%u\n", COMPILER_NAME, COMPILER_VERSION, COMPILER_REVISION );
    DPRINTF("\r\nCORE0 Lockstep         [%s]"ENDLINE, core0_lockstep_en ? "ENABLED" : "DISABLED");
    DPRINTF("CORE1 Lockstep         [%s]"ENDLINE, core1_lockstep_en ? "ENABLED" : "DISABLED");
    DPRINTF("LBIST                  [%s]"ENDLINE, str);
    DPRINTF("MONBIST                [%s]"ENDLINE, monbist_status ? "PASSED" : "FAILED");
    DPRINTF("MCU_FW                 [%s]"ENDLINE, ebcmStatus.sswStatus.mcuFwChkStatus == PASSED ? "PASSED" : "FAILED");
    DPRINTF("MCU_STARTUP            [%s]"ENDLINE, ebcmStatus.sswStatus.mcuStartupStatus ? "OK" : "NOK");
    DPRINTF("SMU_ALIVE_ALARM        [%s]"ENDLINE, ebcmStatus.sswStatus.aliveAlarmStatus ? "OK" : "NOK");
    DPRINTF("SMU_REGISTER_MONITOR   [%s]"ENDLINE, ebcmStatus.smuStatus.regMonitorTestSmu ? "PASSED" : "FAILED");
    DPRINTF("SRAM_BIST              [%s]\r\n"ENDLINE, ebcmStatus.sswStatus.mbistStatus  ? "PASSED" : "FAILED");
    DPRINTF("Safe SW boot procedure completed.\r\n"ENDLINE);

    /* Wait for CPU sync event */


    EbcmHw_initEbcm(&ebcmInfo, IfxCpu_ResourceCpu_0);
    EbcmSch_InitStm(&cpuStm0, (IfxCpu_ResourceCpu)IfxCpu_getCoreIndex());

    while(1)
    {

        EbcmSch_runTasks((IfxCpu_ResourceCpu)IfxCpu_getCoreIndex());
    }
}
