/**********************************************************************************************************************
 * \file ASCLIN_Shell_UART.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "shell.h"
#include "Ifx_Types.h"
#include "IfxAsclin_Asc.h"
#include "Ifx_Shell.h"
#include "Ifx_Console.h"
#include "IfxPort.h"
#include "IfxScu_reg.h"
#include "ebcm_main.h"
#include "ebcm_sched.h"
#include "ssw.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* Communication parameters */
#define ISR_PRIORITY_ASCLIN_TX      10                                       /* Priority for interrupt ISR Transmit  */
#define ISR_PRIORITY_ASCLIN_RX      4                                       /* Priority for interrupt ISR Receive   */
#define ISR_PRIORITY_ASCLIN_ER      12                                      /* Priority for interrupt ISR Errors    */
#define ASC_TX_BUFFER_SIZE          256                                     /* Define the TX buffer size in byte    */
#define ASC_RX_BUFFER_SIZE          256                                     /* Define the RX buffer size in byte    */
#define ASC_BAUDRATE                115200                                  /* Define the UART baud rate            */

/* Shell commands and help descriptions */
#define COMMAND_INFO                "info"
#define COMMAND_SCHED               "sched"
#define COMMAND_SCHED_HELP_TEXT     "  : Display scheduler state and overruns"
#define COMMAND_INFO_HELP_TEXT      "  : Show the boot up info"

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void initSerialInterface(void);
void printInfo(IfxStdIf_DPipe *io);
boolean printShellInfo(pchar args, void *data, IfxStdIf_DPipe *io);

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxStdIf_DPipe gAscStandardInterface;                                     /* Standard interface object            */
IfxAsclin_Asc gAsclin;                                                    /* ASCLIN module object                 */
Ifx_Shell gShellInterface;                                                /* Shell interface object               */
Ifx_Fifo taskOverrunDataFifos[3U];

/* The transfer buffers allocate memory for the data itself and for FIFO runtime variables.
 * 8 more bytes have to be added to ensure a proper circular buffer handling independent from
 * the address to which the buffers have been located.
 */
uint8 gUartTxBuffer[ASC_TX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
uint8 gUartRxBuffer[ASC_RX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];

/* Array that stores the supported Shell commands */
const Ifx_Shell_Command gShellCommands[] = {
    {COMMAND_INFO,   COMMAND_INFO_HELP_TEXT,    &gShellInterface, &printShellInfo     },
    {COMMAND_SCHED,  COMMAND_SCHED_HELP_TEXT,   &gShellInterface, &Ifx_Shell_showHelp},
    IFX_SHELL_COMMAND_LIST_END
};

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Macro to define Interrupt Service Routine.
 * This macro makes following definitions:
 * 1) Define linker section as .intvec_tc<vector number>_<interrupt priority>.
 * 2) define compiler specific attribute for the interrupt functions.
 * 3) define the Interrupt service routine as ISR function.
 *
 * IFX_INTERRUPT(isr, vectabNum, priority)
 *  - isr: Name of the ISR function.
 *  - vectabNum: Vector table number.
 *  - priority: Interrupt priority. Refer Usage of Interrupt Macro for more details.
 */
IFX_INTERRUPT(asc0TxISR, 0, ISR_PRIORITY_ASCLIN_TX);

void asc0TxISR(void)
{
    IfxStdIf_DPipe_onTransmit(&gAscStandardInterface);
}

IFX_INTERRUPT(asc0RxISR, 0, ISR_PRIORITY_ASCLIN_RX);

void asc0RxISR(void)
{
    IfxStdIf_DPipe_onReceive(&gAscStandardInterface);
}

IFX_INTERRUPT(asc0ErrISR, 0, ISR_PRIORITY_ASCLIN_ER);

void asc0ErrISR(void)
{
    IfxStdIf_DPipe_onError(&gAscStandardInterface);
}

/* Function to print info in the console */
void printInfo(IfxStdIf_DPipe *io)
{
    SswTestStatus status = ebcmStatus.sswStatus.lbistStatus;
    const char* str = (const char*)EbcmSsw_getLbistResultStr(status);

    uint8 core0LockstepEn = MODULE_SCU.LCLCON0.B.LS0;
    uint8 core1LockstepEn = MODULE_SCU.LCLCON1.B.LS1;
    uint8 monbistStatus    = PMS_MONBISTSTAT.B.TSTOK;


    IfxStdIf_DPipe_print(io, ENDLINE);
    IfxStdIf_DPipe_print(io, "\r\nAnti-Lock Braking System FW Ver V0R0A     \r\n"ENDLINE);
    IfxStdIf_DPipe_print(io, "\r\nCORE0 Lockstep         [%s]"ENDLINE, core0LockstepEn ? "ENABLED" : "DISABLED");
    IfxStdIf_DPipe_print(io, "CORE1 Lockstep         [%s]"ENDLINE, core1LockstepEn ? "ENABLED" : "DISABLED");
    IfxStdIf_DPipe_print(io, "LBIST                  [%s]"ENDLINE, str);
    IfxStdIf_DPipe_print(io, "MONBIST                [%s]"ENDLINE, monbistStatus ? "PASSED" : "FAILED");
    IfxStdIf_DPipe_print(io, "MCU_FW                 [%s]"ENDLINE, ebcmStatus.sswStatus.mcuFwChkStatus == PASSED ? "PASSED" : "FAILED");
    IfxStdIf_DPipe_print(io, "MCU_STARTUP            [%s]"ENDLINE, ebcmStatus.sswStatus.mcuStartupStatus ? "OK" : "NOK");
    IfxStdIf_DPipe_print(io, "SMU_ALIVE_ALARM        [%s]"ENDLINE, ebcmStatus.sswStatus.aliveAlarmStatus ? "OK" : "NOK");
    IfxStdIf_DPipe_print(io, "SMU_REGISTER_MONITOR   [%s]"ENDLINE, ebcmStatus.smuStatus.regMonitorTestSmu ? "PASSED" : "FAILED");
    IfxStdIf_DPipe_print(io, "SRAM_BIST              [%s]\r\n"ENDLINE, ebcmStatus.sswStatus.mbistStatus  ? "PASSED" : "FAILED");
    IfxStdIf_DPipe_print(io, "Safe SW boot procedure completed.\r\n"ENDLINE);
}

/* Function to show information about the example through the shell */
boolean printShellInfo(pchar args, void *data, IfxStdIf_DPipe *io)
{
    printInfo(io);
    return TRUE;
}

/* Function to initialize ASCLIN module */
void initSerialInterface(void)
{
    IfxAsclin_Asc_Config ascConf;

    /* Set default configurations */
    IfxAsclin_Asc_initModuleConfig(&ascConf, &MODULE_ASCLIN0); /* Initialize the structure with default values      */

    /* Set the desired ` rate */
    ascConf.baudrate.baudrate = ASC_BAUDRATE;                                   /* Set the baud rate in bit/s       */
    ascConf.baudrate.oversampling = IfxAsclin_OversamplingFactor_16;            /* Set the oversampling factor      */

    /* Configure the sampling mode */
    ascConf.bitTiming.medianFilter = IfxAsclin_SamplesPerBit_three;             /* Set the number of samples per bit*/
    ascConf.bitTiming.samplePointPosition = IfxAsclin_SamplePointPosition_8;    /* Set the first sample position    */

    /* ISR priorities and interrupt target */
    ascConf.interrupt.txPriority = ISR_PRIORITY_ASCLIN_TX;  /* Set the interrupt priority for TX events             */
    ascConf.interrupt.rxPriority = ISR_PRIORITY_ASCLIN_RX;  /* Set the interrupt priority for RX events             */
    ascConf.interrupt.erPriority = ISR_PRIORITY_ASCLIN_ER;  /* Set the interrupt priority for Error events          */
    ascConf.interrupt.typeOfService = IfxSrc_Tos_cpu0;

    /* Pin configuration */
    const IfxAsclin_Asc_Pins pins = {
            .cts        = NULL_PTR,                         /* CTS pin not used                                     */
            .ctsMode    = IfxPort_InputMode_pullUp,
            .rx         = &IfxAsclin0_RXA_P14_1_IN,         /* Select the pin for RX connected to the USB port      */
            .rxMode     = IfxPort_InputMode_pullUp,         /* RX pin                                               */
            .rts        = NULL_PTR,                         /* RTS pin not used                                     */
            .rtsMode    = IfxPort_OutputMode_pushPull,
            .tx         = &IfxAsclin0_TX_P14_0_OUT,         /* Select the pin for TX connected to the USB port      */
            .txMode     = IfxPort_OutputMode_pushPull,      /* TX pin                                               */
            .pinDriver  = IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    ascConf.pins = &pins;

    /* FIFO buffers configuration */
    ascConf.txBuffer = gUartTxBuffer;                      /* Set the transmission buffer                          */
    ascConf.txBufferSize = ASC_TX_BUFFER_SIZE;              /* Set the transmission buffer size                     */
    ascConf.rxBuffer = gUartRxBuffer;                      /* Set the receiving buffer                             */
    ascConf.rxBufferSize = ASC_RX_BUFFER_SIZE;              /* Set the receiving buffer size                        */

    /* Init ASCLIN module */
    IfxAsclin_Asc_initModule(&gAsclin, &ascConf);          /* Initialize the module with the given configuration   */
}

/* Function to initialize the Shell */
void initShellInterface(void)
{
    /* Initialize the hardware peripherals */
    initSerialInterface();

    /* Initialize the Standard Interface */
    IfxStdIf_DPipe_ascInit(&gAscStandardInterface, &gAsclin);

    /* Initialize the Console */
    Ifx_Console_init(&gAscStandardInterface);

    /* Print info to the console */
    printInfo(&gAscStandardInterface);

    /* Initialize the shell */
    Ifx_Shell_Config shellConf;
    Ifx_Shell_initConfig(&shellConf);                       /* Initialize the structure with default values         */

    shellConf.standardIo = &gAscStandardInterface;         /* Set a pointer to the standard interface              */
    shellConf.commandList[0] = &gShellCommands[0];         /* Set the supported command list                       */

    Ifx_Shell_init(&gShellInterface, &shellConf);          /* Initialize the Shell with the given configuration    */
}

/* Function to process the incoming received data */
void runShellInterface(void)
{
    /* Process the received data */
    Ifx_Shell_process(&gShellInterface);

    // will pull this out into its own diagnostics function/module, but okay for now
    for (uint8 i = 0; i < 3; i++)
    {
      //  Ifx_SizeT count = Ifx_Fifo_read(&taskOverrunDataFifos[i], (void*) &report , 1, 0);

      // if (count)
        {

        //     IfxStdIf_DPipe_print(&gAscStandardInterface, "CRITICAL: Scheduler overrun - task: %s elapsed time %llu\r\n", report.task.funcName, report.elapsedUs);

        }
    }
}
