/**********************************************************************************************************************
 * \file ASCLIN_Shell_UART.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "shell.h"
#include "Ifx_Types.h"
#include "Ifx_Shell.h"
#include "Ifx_Console.h"
#include "IfxScu_reg.h"
#include "ebcm_main.h"
#include "ebcm_sched.h"
#include "ssw.h"
#include "vfw_checkpoint.h"
#include <string.h>

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* Shell commands and help descriptions */
#define COMMAND_INFO                "info"
#define COMMAND_STATUS              "status"
#define COMMAND_SCHED               "sched"
#define COMMAND_FAULT               "fault"
#define COMMAND_HELP                "help"
#define COMMAND_VFW                 "vfw"
#define COMMAND_INFO_HELP_TEXT      "  : Show platform and safety status"
#define COMMAND_STATUS_HELP_TEXT    "  : Show system status summary"
#define COMMAND_SCHED_HELP_TEXT     "  : Display scheduler state and counters"
#define COMMAND_FAULT_HELP_TEXT     "  : Fault injection controls (arm, disarm, lockstep, status)"
#define COMMAND_HELP_HELP_TEXT      "  : Show this help list"

#ifndef EBCM_SHELL_ENABLE_FAULTS
#define EBCM_SHELL_ENABLE_FAULTS    1
#endif

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void printInfo(IfxStdIf_DPipe *io);
boolean printShellStatus(pchar args, void *data, IfxStdIf_DPipe *io);
boolean printShellSched(pchar args, void *data, IfxStdIf_DPipe *io);
boolean shellFaultCommand(pchar args, void *data, IfxStdIf_DPipe *io);
boolean printShellInfo(pchar args, void *data, IfxStdIf_DPipe *io);

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
Ifx_Shell       g_shellInterface;                                           /* Shell interface object               */
extern IfxStdIf_DPipe g_ascStandardInterface;

/* Array that stores the supported Shell commands */
const Ifx_Shell_Command g_shellCommands[] = {
    {COMMAND_INFO,   COMMAND_INFO_HELP_TEXT,    &g_shellInterface, &printShellInfo   },
    {COMMAND_STATUS, COMMAND_STATUS_HELP_TEXT,  &g_shellInterface, &printShellStatus },
    {COMMAND_SCHED,  COMMAND_SCHED_HELP_TEXT,   &g_shellInterface, &printShellSched  },
    {COMMAND_FAULT,  COMMAND_FAULT_HELP_TEXT,   &g_shellInterface, &shellFaultCommand},
    {COMMAND_HELP,   COMMAND_HELP_HELP_TEXT,    &g_shellInterface, &Ifx_Shell_showHelp},
    IFX_SHELL_COMMAND_LIST_END
};

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Function to print info in the console */
void printInfo(IfxStdIf_DPipe *io)
{
    SswTestStatus status = ebcmStatus.sswStatus.lbistStatus;
    const char* str = (const char*) EbcmSsw_getLbistResultStr(status);

    uint8 core0_lockstep_en = MODULE_SCU.LCLCON0.B.LS0;
    uint8 core1_lockstep_en = MODULE_SCU.LCLCON1.B.LS1;
    uint8 monbist_status    = PMS_MONBISTSTAT.B.TSTOK;


    IfxStdIf_DPipe_print(io, ENDLINE);
    IfxStdIf_DPipe_print(io, "Anti-Lock Braking System FW Ver V0R0A     "ENDLINE);
    IfxStdIf_DPipe_print(io, "Debug shell executing from Core: %u"ENDLINE, __mfcr(CPU_CORE_ID));
    IfxStdIf_DPipe_print(io, "\r\nCORE0 Lockstep         [%s]"ENDLINE, core0_lockstep_en ? "ENABLED" : "DISABLED");
    IfxStdIf_DPipe_print(io, "CORE1 Lockstep         [%s]"ENDLINE, core1_lockstep_en ? "ENABLED" : "DISABLED");
    IfxStdIf_DPipe_print(io, "LBIST                  [%s]"ENDLINE, str);
    IfxStdIf_DPipe_print(io, "MONBIST                [%s]"ENDLINE, monbist_status ? "PASSED" : "FAILED");
    IfxStdIf_DPipe_print(io, "MCU_FW                 [%s]"ENDLINE, ebcmStatus.sswStatus.mcuFwChkStatus == PASSED ? "PASSED" : "FAILED");
    IfxStdIf_DPipe_print(io, "MCU_STARTUP            [%s]"ENDLINE, ebcmStatus.sswStatus.mcuStartupStatus ? "OK" : "NOK");
    IfxStdIf_DPipe_print(io, "SMU_ALIVE_ALARM        [%s]"ENDLINE, ebcmStatus.sswStatus.aliveAlarmStatus ? "OK" : "NOK");
    IfxStdIf_DPipe_print(io, "SMU_REGISTER_MONITOR   [%s]"ENDLINE, ebcmStatus.smuStatus.regMonitorTestSmu ? "PASSED" : "FAILED");
    IfxStdIf_DPipe_print(io, "SRAM_BIST              [%s]\r\n"ENDLINE, ebcmStatus.sswStatus.mbistStatus  ? "PASSED" : "FAILED");

}

/* Function to show information about the example through the shell */
boolean printShellInfo(pchar args, void *data, IfxStdIf_DPipe *io)
{
    printInfo(io);
    return TRUE;
}

static pchar shellSkipSpaces(pchar args)
{
    while (*args == ' ' || *args == '\t')
    {
        args++;
    }
    return args;
}

static boolean shellParseToken(pchar args, char *token, uint16 tokenSize, pchar *next)
{
    uint16 idx = 0U;

    args = shellSkipSpaces(args);
    if (*args == '\0')
    {
        token[0] = '\0';
        if (next != NULL_PTR)
        {
            *next = args;
        }
        return FALSE;
    }

    while ((*args != '\0') && (*args != ' ') && (*args != '\t'))
    {
        if ((idx + 1U) < tokenSize)
        {
            token[idx++] = *args;
        }
        args++;
    }

    token[idx] = '\0';
    if (next != NULL_PTR)
    {
        *next = args;
    }

    return TRUE;
}

boolean printShellStatus(pchar args, void *data, IfxStdIf_DPipe *io)
{
    boolean vfwIntegrityFailed = VFW_HasIntegrityCheckFailed();

    printInfo(io);
    IfxStdIf_DPipe_print(io, "VFW Integrity           [%s]" ENDLINE, vfwIntegrityFailed ? "FAILED" : "OK");
    IfxStdIf_DPipe_print(io, "Reset Code              [%u]" ENDLINE, (uint32) ebcmStatus.resetCode.resetType);
    IfxStdIf_DPipe_print(io, "Wake From Standby       [%s]" ENDLINE, ebcmStatus.wakeupFromStby ? "YES" : "NO");

    return TRUE;
}

boolean printShellSched(pchar args, void *data, IfxStdIf_DPipe *io)
{
    const char *core0Task = (core0_currentTask != NULL_PTR) ? core0_currentTask->funcName : "NONE";
    const char *core1Task = (core1_currentTask != NULL_PTR) ? core1_currentTask->funcName : "NONE";

    IfxStdIf_DPipe_print(io, "Scheduler Counters" ENDLINE);
    IfxStdIf_DPipe_print(io, "  core0=%lu core1=%lu core2=%lu" ENDLINE,
                         (uint32) cpu0execTaskCounter,
                         (uint32) cpu1execTaskCounter,
                         (uint32) cpu2execTaskCounter);
    IfxStdIf_DPipe_print(io, "Current Task" ENDLINE);
    IfxStdIf_DPipe_print(io, "  core0=%s" ENDLINE, core0Task);
    IfxStdIf_DPipe_print(io, "  core1=%s" ENDLINE, core1Task);

    return TRUE;
}

boolean shellFaultCommand(pchar args, void *data, IfxStdIf_DPipe *io)
{
    char token[16];
    static boolean faultArmed = FALSE;

    if (!shellParseToken(args, token, sizeof(token), NULL_PTR))
    {
        IfxStdIf_DPipe_print(io, "Usage: fault <arm|disarm|lockstep|status>" ENDLINE);
        return FALSE;
    }

    if (strcmp(token, "arm") == 0)
    {
        faultArmed = TRUE;
        IfxStdIf_DPipe_print(io, "Fault injection armed for next command." ENDLINE);
        return TRUE;
    }

    if (strcmp(token, "disarm") == 0)
    {
        faultArmed = FALSE;
        IfxStdIf_DPipe_print(io, "Fault injection disarmed." ENDLINE);
        return TRUE;
    }

    if (strcmp(token, "status") == 0)
    {
        IfxStdIf_DPipe_print(io, "Fault injection %s" ENDLINE, faultArmed ? "ARMED" : "DISARMED");
        IfxStdIf_DPipe_print(io, "Fault controls %s" ENDLINE, EBCM_SHELL_ENABLE_FAULTS ? "ENABLED" : "DISABLED");
        return TRUE;
    }

    if (strcmp(token, "lockstep") == 0)
    {
#if EBCM_SHELL_ENABLE_FAULTS
        if (!faultArmed)
        {
            IfxStdIf_DPipe_print(io, "Fault injection not armed. Use 'fault arm'." ENDLINE);
            return FALSE;
        }

        faultArmed = FALSE;
        IfxStdIf_DPipe_print(io, "Injecting lockstep comparator fault..." ENDLINE);
        IfxStdIf_DPipe_print(io, "Result: %s" ENDLINE, EbcmSsw_lockstepInjectionTest() ? "PASSED" : "FAILED");
#else
        IfxStdIf_DPipe_print(io, "Fault injection disabled in this build." ENDLINE);
#endif
        return TRUE;
    }

    IfxStdIf_DPipe_print(io, "Unknown fault command. Use 'fault status'." ENDLINE);
    return FALSE;
}

/* Function to initialize the Shell */
void initShellInterface(void)
{
    /* Initialize the Console */
    Ifx_Console_init(&g_ascStandardInterface);

    /* Print info to the console */
    printInfo(&g_ascStandardInterface);

    /* Initialize the shell */
    Ifx_Shell_Config shellConf;
    Ifx_Shell_initConfig(&shellConf);                       /* Initialize the structure with default values         */

    shellConf.standardIo = &g_ascStandardInterface;         /* Set a pointer to the standard interface              */
    shellConf.commandList[0] = &g_shellCommands[0];         /* Set the supported command list                       */

    Ifx_Shell_init(&g_shellInterface, &shellConf);          /* Initialize the Shell with the given configuration    */
}

/* Function to process the incoming received data */
void runShellInterface(void)
{
    /* Process the received data */
    Ifx_Shell_process(&g_shellInterface);
}
